// 480x272 parallel RGB888 text console for the AN340-class DE-mode LCD on
// J20. Pipeline is a clone of hdmi_text_console_core (clear scan on sys_clk,
// 3-stage pixel pipe, 16-colour palette) minus the TMDS encoders: output is a
// registered same-beat snapshot of RGB + DE + HS + VS. DCLK is generated by
// the board top from a 180-degree MMCM tap, so the panel samples at the edge
// opposite to our updates (see lcd_console_top_xilinx.v).
//
// Geometry: 60 cols x 17 rows of 8x16 cells tile the panel exactly
// (60*8 = 480, 17*16 = 272). text/attr/font are dual-clock BRAMs written from
// the sys domain (via mmio_lcd_display_ctrl) and read in the pix domain.
//
// Clear-scan width is CLEAR_WORDS = 256, deliberately one word deeper than the
// 255 text words: the attr clear fires on odd clear indices and 255 is odd,
// so scanning 0..255 covers all 128 attr words (word 127 on index 255). Host
// text writes are still guarded to < TEXT_WORDS = 255.
module lcd_text_console_core #(
    parameter int TEXT_COLS = 60,
    parameter int TEXT_ROWS = 17,
    parameter int TEXT_CELLS = TEXT_COLS * TEXT_ROWS,        // 1020
    parameter int TEXT_WORDS = TEXT_CELLS / 4,               // 255
    parameter int ATTR_WORDS = (TEXT_CELLS + 7) / 8,        // 128
    parameter int CLEAR_WORDS = 256                          // see header
) (
    input  logic        sys_clk,
    input  logic        pix_clk,
    input  logic        rst_n,
    input  logic        pix_rst_n,
    input  logic        enable,
    input  logic        text_enable,
    input  logic        text_clear,
    input  logic [1:0]  mode,        // must be 2'd3 (480x272)
    input  logic [31:0] bg_color,

    input  logic        text_we,
    input  logic [7:0]  text_word_addr,
    input  logic [31:0] text_wdata,
    input  logic [3:0]  text_wstrb,
    input  logic        attr_we,
    input  logic [6:0]  attr_word_addr,
    input  logic [31:0] attr_wdata,
    input  logic [3:0]  attr_wstrb,
    input  logic        font_we,
    input  logic [8:0]  font_word_addr,
    input  logic [31:0] font_wdata,
    input  logic [3:0]  font_wstrb,

    output logic [7:0]  lcd_r,
    output logic [7:0]  lcd_g,
    output logic [7:0]  lcd_b,
    output logic        lcd_de,
    output logic        lcd_hs,
    output logic        lcd_vs,
    output logic [15:0] h_count,
    output logic [15:0] v_count,
    output logic        frame_done
);
    logic [15:0] width;
    logic [15:0] height;
    logic        hsync;
    logic        vsync;
    logic        active;
    logic        frame_start;
    logic [7:0]  base_red;
    logic [7:0]  base_green;
    logic [7:0]  base_blue;

    logic        clear_active;
    logic [8:0]  clear_index;
    logic [7:0]  attr_clear_index;
    logic        text_ram_we;
    logic [7:0]  text_ram_waddr;
    logic [31:0] text_ram_wdata;
    logic        attr_ram_we;
    logic [6:0]  attr_ram_waddr;
    logic [31:0] attr_ram_wdata;

    logic [13:0] text_read_cell_addr;
    logic [7:0]  text_read_word_addr;
    logic [6:0]  attr_read_word_addr;
    logic [1:0]  text_read_byte_lane;
    logic [2:0]  attr_nibble_lane;
    logic [1:0]  text_byte_lane;
    logic [2:0]  attr_lane_q;
    logic [31:0] text_word;
    logic [31:0] attr_word;
    logic [7:0]  text_ch;
    logic [3:0]  text_attr;
    logic [2:0]  glyph_x;
    logic [3:0]  glyph_row;
    logic [10:0] font_read_byte_addr;
    logic [8:0]  font_read_word_addr;
    logic [1:0]  font_read_byte_lane;
    logic [1:0]  glyph_byte_lane_q;
    logic [31:0] glyph_word;
    logic [7:0]  glyph_bits;
    logic [7:0]  glyph_bits_q;
    logic [7:0]  text_ch_q;
    logic [7:0]  text_ch_qq;
    logic [3:0]  text_attr_q;
    logic [3:0]  text_attr_qq;
    logic [2:0]  glyph_x_q;
    logic [2:0]  glyph_x_qq;
    logic        text_pixel;
    logic [7:0]  glyph_red;
    logic [7:0]  glyph_green;
    logic [7:0]  glyph_blue;
    logic [7:0]  cell_bg_red;
    logic [7:0]  cell_bg_green;
    logic [7:0]  cell_bg_blue;
    logic        text_active_d;
    logic        text_active_q;
    logic        text_active_qq;
    logic        active_d;
    logic        active_q;
    logic        active_qq;
    logic        hsync_d;
    logic        hsync_q;
    logic        hsync_qq;
    logic        vsync_d;
    logic        vsync_q;
    logic        vsync_qq;
    logic [7:0]  red_d;
    logic [7:0]  red_q;
    logic [7:0]  red_qq;
    logic [7:0]  green_d;
    logic [7:0]  green_q;
    logic [7:0]  green_qq;
    logic [7:0]  blue_d;
    logic [7:0]  blue_q;
    logic [7:0]  blue_qq;
    logic        enable_meta;
    logic        enable_pix;
    logic        text_enable_meta;
    logic        text_enable_pix;
    logic [31:0] bg_color_meta;
    logic [31:0] bg_color_pix;
    logic [15:0] text_x;
    logic [15:0] text_y;
    logic        text_visible;
    logic [7:0]  text_row_index;
    logic [5:0]  text_col_index;

    video_timing u_timing (
        .clk(pix_clk),
        .rst_n(pix_rst_n),
        .enable(enable_pix),
        .mode(mode),
        .h_count(h_count),
        .v_count(v_count),
        .active_width(width),
        .active_height(height),
        .hsync(hsync),
        .vsync(vsync),
        .active(active),
        .frame_start(frame_start),
        .frame_done(frame_done)
    );

    always_comb begin
        if (!active) begin
            base_red = 8'd0;
            base_green = 8'd0;
            base_blue = 8'd0;
        end else begin
            base_red = bg_color_pix[23:16];
            base_green = bg_color_pix[15:8];
            base_blue = bg_color_pix[7:0];
        end
    end

    assign text_ram_we = clear_active || (text_we && text_word_addr < TEXT_WORDS && text_wstrb != 4'd0);
    assign text_ram_waddr = clear_active ? clear_index[7:0] : text_word_addr;
    assign text_ram_wdata = clear_active ? 32'h2020_2020 : text_wdata;
    assign attr_clear_index = clear_index[8:1];
    assign attr_ram_we = (clear_active && clear_index[0]) ||
                         (attr_we && attr_word_addr < ATTR_WORDS && attr_wstrb != 4'd0);
    assign attr_ram_waddr = clear_active ? attr_clear_index : {1'b0, attr_word_addr};
    assign attr_ram_wdata = clear_active ? 32'h7777_7777 : attr_wdata;

    always_ff @(posedge sys_clk) begin
        if (!rst_n) begin
            clear_active <= 1'b1;
            clear_index <= 9'd0;
        end else begin
            if (text_clear) begin
                clear_active <= 1'b1;
                clear_index <= 9'd0;
            end else if (clear_active) begin
                if (clear_index == CLEAR_WORDS - 1) begin
                    clear_active <= 1'b0;
                end else begin
                    clear_index <= clear_index + 9'd1;
                end
            end
        end
    end

    hdmi_console_ram #(
        .ADDR_WIDTH(8),
        .DATA_WIDTH(32),
        .DEPTH(256)
    ) u_text_ram (
        .wr_clk(sys_clk),
        .wr_en(text_ram_we),
        .wr_addr(text_ram_waddr),
        .wr_data(text_ram_wdata),
        .rd_clk(pix_clk),
        .rd_addr(text_read_word_addr),
        .rd_data(text_word)
    );

    hdmi_console_ram #(
        .ADDR_WIDTH(7),
        .DATA_WIDTH(32),
        .DEPTH(128)
    ) u_attr_ram (
        .wr_clk(sys_clk),
        .wr_en(attr_ram_we),
        .wr_addr(attr_ram_waddr),
        .wr_data(attr_ram_wdata),
        .rd_clk(pix_clk),
        .rd_addr(attr_read_word_addr),
        .rd_data(attr_word)
    );

    hdmi_console_ram #(
        .ADDR_WIDTH(9),
        .DATA_WIDTH(32),
        .DEPTH(512)
    ) u_font_ram (
        .wr_clk(sys_clk),
        .wr_en(font_we && font_wstrb != 4'd0),
        .wr_addr(font_word_addr),
        .wr_data(font_wdata),
        .rd_clk(pix_clk),
        .rd_addr(font_read_word_addr),
        .rd_data(glyph_word)
    );

    assign text_x = h_count;
    assign text_y = v_count;
    assign text_visible = h_count < (TEXT_COLS[15:0] * 16'd8) &&
                          v_count < (TEXT_ROWS[15:0] * 16'd16);
    assign text_row_index = text_y[11:4];
    assign text_col_index = text_x[9:3];

    always_comb begin
        text_read_cell_addr = 14'd0;
        if (text_visible) begin
            text_read_cell_addr = (text_row_index * TEXT_COLS) + text_col_index;
        end
        text_read_word_addr = text_read_cell_addr[9:2];
        attr_read_word_addr = text_read_cell_addr[9:3];
        text_read_byte_lane = text_read_cell_addr[1:0];
        attr_nibble_lane = text_read_cell_addr[2:0];
    end

    always_comb begin
        font_read_byte_addr = {text_ch[6:0], glyph_row};
        font_read_word_addr = font_read_byte_addr[10:2];
        font_read_byte_lane = font_read_byte_addr[1:0];
    end

    always_ff @(posedge pix_clk or negedge pix_rst_n) begin
        if (!pix_rst_n) begin
            enable_meta <= 1'b0;
            enable_pix <= 1'b0;
            text_enable_meta <= 1'b0;
            text_enable_pix <= 1'b0;
            bg_color_meta <= 32'd0;
            bg_color_pix <= 32'd0;
        end else begin
            enable_meta <= enable;
            enable_pix <= enable_meta;
            text_enable_meta <= text_enable;
            text_enable_pix <= text_enable_meta;
            bg_color_meta <= bg_color;
            bg_color_pix <= bg_color_meta;
        end
    end

    always_ff @(posedge pix_clk or negedge pix_rst_n) begin
        if (!pix_rst_n) begin
            text_byte_lane <= 2'd0;
            attr_lane_q <= 3'd0;
            glyph_x <= 3'd0;
            glyph_row <= 3'd0;
            glyph_byte_lane_q <= 2'd0;
            glyph_bits_q <= 8'd0;
            text_ch_q <= 8'h20;
            text_ch_qq <= 8'h20;
            text_attr_q <= 4'h7;
            text_attr_qq <= 4'h7;
            glyph_x_q <= 3'd0;
            glyph_x_qq <= 3'd0;
            text_active_d <= 1'b0;
            text_active_q <= 1'b0;
            text_active_qq <= 1'b0;
            active_d <= 1'b0;
            active_q <= 1'b0;
            active_qq <= 1'b0;
            hsync_d <= 1'b1;
            hsync_q <= 1'b1;
            hsync_qq <= 1'b1;
            vsync_d <= 1'b1;
            vsync_q <= 1'b1;
            vsync_qq <= 1'b1;
            red_d <= 8'd0;
            red_q <= 8'd0;
            red_qq <= 8'd0;
            green_d <= 8'd0;
            green_q <= 8'd0;
            green_qq <= 8'd0;
            blue_d <= 8'd0;
            blue_q <= 8'd0;
            blue_qq <= 8'd0;
            lcd_de <= 1'b0;
        end else begin
            text_byte_lane <= text_read_byte_lane;
            attr_lane_q <= attr_nibble_lane;
            glyph_x <= text_x[2:0];
            glyph_row <= text_y[3:0];
            glyph_byte_lane_q <= font_read_byte_lane;
            glyph_bits_q <= glyph_bits;
            text_ch_q <= text_ch;
            text_ch_qq <= text_ch_q;
            text_attr_q <= text_attr;
            text_attr_qq <= text_attr_q;
            glyph_x_q <= glyph_x;
            glyph_x_qq <= glyph_x_q;
            text_active_d <= text_enable_pix && active && text_visible;
            text_active_q <= text_active_d;
            text_active_qq <= text_active_q;
            active_d <= active;
            active_q <= active_d;
            active_qq <= active_q;
            hsync_d <= hsync;
            hsync_q <= hsync_d;
            hsync_qq <= hsync_q;
            vsync_d <= vsync;
            vsync_q <= vsync_d;
            vsync_qq <= vsync_q;
            red_d <= base_red;
            red_q <= red_d;
            red_qq <= red_q;
            green_d <= base_green;
            green_q <= green_d;
            green_qq <= green_q;
            blue_d <= base_blue;
            blue_q <= blue_d;
            blue_qq <= blue_q;
            // Pad outputs: RGB/DE/HS/VS leave as ONE registered snapshot, so
            // the panel sees mutually aligned signals (classes scan.v rule).
            // HS/VS idle high between pulses (DE-mode, low-active).
            lcd_r <= text_pixel ? glyph_red : (text_active_qq ? cell_bg_red : red_qq);
            lcd_g <= text_pixel ? glyph_green : (text_active_qq ? cell_bg_green : green_qq);
            lcd_b <= text_pixel ? glyph_blue : (text_active_qq ? cell_bg_blue : blue_qq);
            lcd_de <= active_qq;
            lcd_hs <= hsync_qq;
            lcd_vs <= vsync_qq;
        end
    end

    always_comb begin
        unique case (text_byte_lane)
            2'd0: text_ch = text_word[7:0];
            2'd1: text_ch = text_word[15:8];
            2'd2: text_ch = text_word[23:16];
            default: text_ch = text_word[31:24];
        endcase
    end

    always_comb begin
        unique case (attr_lane_q)
            3'd0: text_attr = attr_word[3:0];
            3'd1: text_attr = attr_word[7:4];
            3'd2: text_attr = attr_word[11:8];
            3'd3: text_attr = attr_word[15:12];
            3'd4: text_attr = attr_word[19:16];
            3'd5: text_attr = attr_word[23:20];
            3'd6: text_attr = attr_word[27:24];
            default: text_attr = attr_word[31:28];
        endcase
    end

    always_comb begin
        unique case (glyph_byte_lane_q)
            2'd0: glyph_bits = glyph_word[7:0];
            2'd1: glyph_bits = glyph_word[15:8];
            2'd2: glyph_bits = glyph_word[23:16];
            default: glyph_bits = glyph_word[31:24];
        endcase
    end

    always_comb begin
        unique case (text_attr_qq)
            4'd0: {glyph_red, glyph_green, glyph_blue} = 24'h000000;
            4'd1: {glyph_red, glyph_green, glyph_blue} = 24'haa0000;
            4'd2: {glyph_red, glyph_green, glyph_blue} = 24'h00aa00;
            4'd3: {glyph_red, glyph_green, glyph_blue} = 24'haa5500;
            4'd4: {glyph_red, glyph_green, glyph_blue} = 24'h0000aa;
            4'd5: {glyph_red, glyph_green, glyph_blue} = 24'haa00aa;
            4'd6: {glyph_red, glyph_green, glyph_blue} = 24'h00aaaa;
            4'd8: {glyph_red, glyph_green, glyph_blue} = 24'h555555;
            4'd9: {glyph_red, glyph_green, glyph_blue} = 24'hff5555;
            4'd10: {glyph_red, glyph_green, glyph_blue} = 24'h55ff55;
            4'd11: {glyph_red, glyph_green, glyph_blue} = 24'hffff55;
            4'd12: {glyph_red, glyph_green, glyph_blue} = 24'h5555ff;
            4'd13: {glyph_red, glyph_green, glyph_blue} = 24'hff55ff;
            4'd14: {glyph_red, glyph_green, glyph_blue} = 24'h55ffff;
            4'd15: {glyph_red, glyph_green, glyph_blue} = 24'hffffff;
            default: {glyph_red, glyph_green, glyph_blue} = 24'he0e0e0;
        endcase
    end

    assign cell_bg_red = 8'h00;
    assign cell_bg_green = 8'h00;
    assign cell_bg_blue = 8'h00;

    assign text_pixel = text_active_qq && (text_ch_qq != 8'h20) && glyph_bits_q[3'd7 - glyph_x_qq];
endmodule
