#ifndef PS_UART_PROBE_H
#define PS_UART_PROBE_H

#include "xil_types.h"

#define ZYNQ_CPU_REG_BASE      0x43C00000U
#define ZYNQ_CPU_BUILD_ID      (ZYNQ_CPU_REG_BASE + 0x00U)
#define ZYNQ_CPU_STATUS        (ZYNQ_CPU_REG_BASE + 0x04U)
#define ZYNQ_CPU_SCRATCH       (ZYNQ_CPU_REG_BASE + 0x08U)
#define ZYNQ_CPU_WRITE_COUNT   (ZYNQ_CPU_REG_BASE + 0x0CU)
#define ZYNQ_CPU_READ_COUNT    (ZYNQ_CPU_REG_BASE + 0x10U)

#define ZYNQ_CPU_DMA_BASE      0x43C10000U
#define ZYNQ_CPU_DMA_CTRL      (ZYNQ_CPU_DMA_BASE + 0x00U)
#define ZYNQ_CPU_DMA_STATUS    (ZYNQ_CPU_DMA_BASE + 0x04U)
#define ZYNQ_CPU_DMA_DDR_ADDR  (ZYNQ_CPU_DMA_BASE + 0x08U)
#define ZYNQ_CPU_DMA_LOCAL     (ZYNQ_CPU_DMA_BASE + 0x0CU)
#define ZYNQ_CPU_DMA_LEN       (ZYNQ_CPU_DMA_BASE + 0x10U)
#define ZYNQ_CPU_DMA_TAG       (ZYNQ_CPU_DMA_BASE + 0x14U)
#define ZYNQ_CPU_RX_SCRATCH    (ZYNQ_CPU_DMA_BASE + 0x1000U)
#define ZYNQ_CPU_TX_SCRATCH    (ZYNQ_CPU_DMA_BASE + 0x2000U)
#define ZYNQ_CPU_IMEM_BASE     (ZYNQ_CPU_DMA_BASE + 0x3000U)
#define ZYNQ_CPU_CTRL_BASE     (ZYNQ_CPU_DMA_BASE + 0x7000U)
#define ZYNQ_CPU_DISPLAY_BASE  (ZYNQ_CPU_DMA_BASE + 0x9000U)
#define ZYNQ_CPU_CPU_CTRL      (ZYNQ_CPU_CTRL_BASE + 0x00U)
#define ZYNQ_CPU_CPU_STATUS    (ZYNQ_CPU_CTRL_BASE + 0x04U)
#define ZYNQ_CPU_BRAM_WORDS    (ZYNQ_CPU_CTRL_BASE + 0x08U)
#define ZYNQ_CPU_SCRATCH_WORDS (ZYNQ_CPU_CTRL_BASE + 0x0CU)
#define ZYNQ_CPU_RESET_VECTOR  (ZYNQ_CPU_CTRL_BASE + 0x10U)
#define ZYNQ_CPU_DBG_STATE     (ZYNQ_CPU_CTRL_BASE + 0x20U)
#define ZYNQ_CPU_DBG_PC        (ZYNQ_CPU_CTRL_BASE + 0x24U)
#define ZYNQ_CPU_DBG_SATP      (ZYNQ_CPU_CTRL_BASE + 0x28U)
#define ZYNQ_CPU_DBG_STVEC     (ZYNQ_CPU_CTRL_BASE + 0x2CU)
#define ZYNQ_CPU_DBG_SEPC      (ZYNQ_CPU_CTRL_BASE + 0x30U)
#define ZYNQ_CPU_DBG_SCAUSE    (ZYNQ_CPU_CTRL_BASE + 0x34U)
#define ZYNQ_CPU_DBG_STVAL     (ZYNQ_CPU_CTRL_BASE + 0x38U)
#define ZYNQ_CPU_DBG_REQ_VADDR (ZYNQ_CPU_CTRL_BASE + 0x3CU)
#define ZYNQ_CPU_DBG_REQ_PADDR (ZYNQ_CPU_CTRL_BASE + 0x40U)
#define ZYNQ_CPU_DBG_PTW_ADDR  (ZYNQ_CPU_CTRL_BASE + 0x44U)
#define ZYNQ_CPU_DBG_PTW_L1    (ZYNQ_CPU_CTRL_BASE + 0x48U)
#define ZYNQ_CPU_DBG_PTW_L0    (ZYNQ_CPU_CTRL_BASE + 0x4CU)
#define ZYNQ_CPU_DBG_BUS       (ZYNQ_CPU_CTRL_BASE + 0x50U)
#define ZYNQ_CPU_DBG_DDR_ADDR  (ZYNQ_CPU_CTRL_BASE + 0x54U)
#define ZYNQ_CPU_DBG_IMEM_ADDR (ZYNQ_CPU_CTRL_BASE + 0x58U)
#define ZYNQ_CPU_DBG_DMEM_ADDR (ZYNQ_CPU_CTRL_BASE + 0x5CU)
#define ZYNQ_CPU_DBG_LAST_DDR_ADDR (ZYNQ_CPU_CTRL_BASE + 0x60U)
#define ZYNQ_CPU_DBG_LAST_DDR_STATE (ZYNQ_CPU_CTRL_BASE + 0x64U)
#define ZYNQ_CPU_DBG_LAST_AXI_ARADDR (ZYNQ_CPU_CTRL_BASE + 0x68U)
#define ZYNQ_CPU_DBG_LAST_IMEM_ADDR (ZYNQ_CPU_CTRL_BASE + 0x6CU)
#define ZYNQ_CPU_DBG_LAST_DMEM_ADDR (ZYNQ_CPU_CTRL_BASE + 0x70U)

#define ZYNQ_CPU_DISPLAY_CONTROL (ZYNQ_CPU_DISPLAY_BASE + 0x00U)
#define ZYNQ_CPU_DISPLAY_MODE    (ZYNQ_CPU_DISPLAY_BASE + 0x14U)
#define ZYNQ_CPU_DISPLAY_BG      (ZYNQ_CPU_DISPLAY_BASE + 0x18U)
#define ZYNQ_CPU_DISPLAY_TEXT_CTRL (ZYNQ_CPU_DISPLAY_BASE + 0x24U)
#define ZYNQ_CPU_DISPLAY_TEXT_BASE (ZYNQ_CPU_DISPLAY_BASE + 0x400U)
#define ZYNQ_CPU_DISPLAY_ATTR_BASE (ZYNQ_CPU_DISPLAY_BASE + 0x4400U)
#define ZYNQ_CPU_DISPLAY_FONT_BASE (ZYNQ_CPU_DISPLAY_BASE + 0x6400U)
#define ZYNQ_CPU_DISPLAY_CONTROL_ENABLE 0x00000001U
#define ZYNQ_CPU_DISPLAY_CONTROL_RESET  0x00000002U
#define ZYNQ_CPU_DISPLAY_CONTROL_TEST   0x00000004U
#define ZYNQ_CPU_DISPLAY_TEXT_ENABLE    0x00000001U
#define ZYNQ_CPU_DISPLAY_TEXT_CLEAR     0x00000002U
#define ZYNQ_CPU_DISPLAY_TEXT_COLS      240U
#define ZYNQ_CPU_DISPLAY_TEXT_ROWS      67U
#define ZYNQ_CPU_DISPLAY_TEXT_CELLS     (ZYNQ_CPU_DISPLAY_TEXT_COLS * ZYNQ_CPU_DISPLAY_TEXT_ROWS)

#define CPU_MAIL_START         (ZYNQ_CPU_TX_SCRATCH + 0x3E0U)
#define CPU_MAIL_SRC           (ZYNQ_CPU_TX_SCRATCH + 0x3E4U)
#define CPU_MAIL_DST           (ZYNQ_CPU_TX_SCRATCH + 0x3E8U)
#define CPU_MAIL_LEN           (ZYNQ_CPU_TX_SCRATCH + 0x3ECU)
#define CPU_MAIL_STATUS        (ZYNQ_CPU_TX_SCRATCH + 0x3F0U)
#define CPU_MAIL_MM2S_STATUS   (ZYNQ_CPU_TX_SCRATCH + 0x3F4U)
#define CPU_MAIL_S2MM_STATUS   (ZYNQ_CPU_TX_SCRATCH + 0x3F8U)
#define CPU_MAIL_COPIED        (ZYNQ_CPU_TX_SCRATCH + 0x3FCU)
#define CPU_SUP_SEPC           (ZYNQ_CPU_TX_SCRATCH + 0x3E0U)
#define CPU_SUP_SCAUSE         (ZYNQ_CPU_TX_SCRATCH + 0x3E4U)
#define CPU_SUP_MARKER         (ZYNQ_CPU_TX_SCRATCH + 0x3E8U)
#define CPU_SUP_STATUS         (ZYNQ_CPU_TX_SCRATCH + 0x3F0U)
#define CPU_BOOT_HARTID        (ZYNQ_CPU_TX_SCRATCH + 0x3C0U)
#define CPU_BOOT_DTB           (ZYNQ_CPU_TX_SCRATCH + 0x3C4U)
#define CPU_BOOT_CYCLE         (ZYNQ_CPU_TX_SCRATCH + 0x3C8U)
#define CPU_BOOT_TIME          (ZYNQ_CPU_TX_SCRATCH + 0x3CCU)
#define CPU_BOOT_INSTRET       (ZYNQ_CPU_TX_SCRATCH + 0x3D0U)
#define CPU_DDR_EXEC_PC        (ZYNQ_CPU_TX_SCRATCH + 0x3C0U)
#define CPU_DDR_EXEC_MARKER    (ZYNQ_CPU_TX_SCRATCH + 0x3C4U)
#define CPU_DDR_EXEC_COUNT     (ZYNQ_CPU_TX_SCRATCH + 0x3C8U)
#define CPU_SBI_PAYLOAD_ENTRY  (ZYNQ_CPU_TX_SCRATCH + 0x380U)
#define CPU_SBI_DTB_ADDR       (ZYNQ_CPU_TX_SCRATCH + 0x384U)
#define CPU_SBI_MCAUSE         (ZYNQ_CPU_TX_SCRATCH + 0x38CU)
#define CPU_SBI_MEPC           (ZYNQ_CPU_TX_SCRATCH + 0x390U)
#define CPU_SBI_EID            (ZYNQ_CPU_TX_SCRATCH + 0x394U)
#define CPU_SBI_ARG0           (ZYNQ_CPU_TX_SCRATCH + 0x398U)
#define CPU_SBI_MARKER         (ZYNQ_CPU_TX_SCRATCH + 0x39CU)
#define CPU_SBI_HARTID         (ZYNQ_CPU_TX_SCRATCH + 0x3A0U)
#define CPU_SBI_PAYLOAD_DTB    (ZYNQ_CPU_TX_SCRATCH + 0x3A4U)
#define CPU_SBI_RETVAL         (ZYNQ_CPU_TX_SCRATCH + 0x3A8U)
#define CPU_SBI_TIMER_ENTRY    (ZYNQ_CPU_TX_SCRATCH + 0x340U)
#define CPU_SBI_TIMER_DTB      (ZYNQ_CPU_TX_SCRATCH + 0x344U)
#define CPU_SBI_TIMER_MCAUSE   (ZYNQ_CPU_TX_SCRATCH + 0x34CU)
#define CPU_SBI_TIMER_MEPC     (ZYNQ_CPU_TX_SCRATCH + 0x350U)
#define CPU_SBI_TIMER_EID      (ZYNQ_CPU_TX_SCRATCH + 0x354U)
#define CPU_SBI_TIMER_FID      (ZYNQ_CPU_TX_SCRATCH + 0x358U)
#define CPU_SBI_TIMER_ARG0     (ZYNQ_CPU_TX_SCRATCH + 0x35CU)
#define CPU_SBI_TIMER_CMP_LO   (ZYNQ_CPU_TX_SCRATCH + 0x360U)
#define CPU_SBI_TIMER_CMP_HI   (ZYNQ_CPU_TX_SCRATCH + 0x364U)
#define CPU_SBI_TIMER_HARTID   (ZYNQ_CPU_TX_SCRATCH + 0x380U)
#define CPU_SBI_TIMER_PAY_DTB  (ZYNQ_CPU_TX_SCRATCH + 0x384U)
#define CPU_SBI_TIMER_RETVAL   (ZYNQ_CPU_TX_SCRATCH + 0x388U)
#define CPU_SBI_TIMER_SCAUSE   (ZYNQ_CPU_TX_SCRATCH + 0x38CU)
#define CPU_SBI_TIMER_SEPC     (ZYNQ_CPU_TX_SCRATCH + 0x390U)
#define CPU_SBI_TIMER_SIE      (ZYNQ_CPU_TX_SCRATCH + 0x394U)
#define CPU_SBI_TIMER_SIP      (ZYNQ_CPU_TX_SCRATCH + 0x398U)
#define CPU_SBI_TIMER_SSTATUS  (ZYNQ_CPU_TX_SCRATCH + 0x39CU)
#define CPU_SBI_TIMER_TIME0    (ZYNQ_CPU_TX_SCRATCH + 0x3A0U)
#define CPU_SBI_TIMER_TIME1    (ZYNQ_CPU_TX_SCRATCH + 0x3A4U)
#define CPU_LINUX_ENTRY        (ZYNQ_CPU_TX_SCRATCH + 0x300U)
#define CPU_LINUX_DTB          (ZYNQ_CPU_TX_SCRATCH + 0x304U)
#define CPU_LINUX_MCAUSE       (ZYNQ_CPU_TX_SCRATCH + 0x308U)
#define CPU_LINUX_MEPC         (ZYNQ_CPU_TX_SCRATCH + 0x30CU)
#define CPU_LINUX_SBI_EID      (ZYNQ_CPU_TX_SCRATCH + 0x310U)
#define CPU_LINUX_SBI_FID      (ZYNQ_CPU_TX_SCRATCH + 0x314U)
#define CPU_LINUX_SBI_ARG0     (ZYNQ_CPU_TX_SCRATCH + 0x318U)
#define CPU_LINUX_SBI_RETVAL   (ZYNQ_CPU_TX_SCRATCH + 0x31CU)
#define CPU_LINUX_CMP_LO       (ZYNQ_CPU_TX_SCRATCH + 0x320U)
#define CPU_LINUX_CMP_HI       (ZYNQ_CPU_TX_SCRATCH + 0x324U)
#define CPU_LINUX_HARTID       (ZYNQ_CPU_TX_SCRATCH + 0x328U)
#define CPU_LINUX_PAYLOAD_DTB  (ZYNQ_CPU_TX_SCRATCH + 0x32CU)
#define CPU_LINUX_DTB_MAGIC    (ZYNQ_CPU_TX_SCRATCH + 0x330U)
#define CPU_LINUX_BASE_VERSION (ZYNQ_CPU_TX_SCRATCH + 0x334U)
#define CPU_LINUX_SCAUSE       (ZYNQ_CPU_TX_SCRATCH + 0x338U)
#define CPU_LINUX_SEPC         (ZYNQ_CPU_TX_SCRATCH + 0x33CU)
#define CPU_LINUX_TIME0        (ZYNQ_CPU_TX_SCRATCH + 0x340U)
#define CPU_LINUX_TIME1        (ZYNQ_CPU_TX_SCRATCH + 0x344U)
#define CPU_LINUX_DTB_TOTAL    (ZYNQ_CPU_TX_SCRATCH + 0x348U)
#define CPU_LINUX_DTB_STRUCT   (ZYNQ_CPU_TX_SCRATCH + 0x34CU)
#define CPU_LINUX_DTB_STRINGS  (ZYNQ_CPU_TX_SCRATCH + 0x350U)
#define CPU_LINUX_FDT_ROOT     (ZYNQ_CPU_TX_SCRATCH + 0x354U)
#define CPU_LINUX_ADDR_CELLS   (ZYNQ_CPU_TX_SCRATCH + 0x358U)
#define CPU_LINUX_SIZE_CELLS   (ZYNQ_CPU_TX_SCRATCH + 0x35CU)
#define CPU_LINUX_FDT_MEMORY   (ZYNQ_CPU_TX_SCRATCH + 0x360U)
#define CPU_LINUX_REG_ADDR     (ZYNQ_CPU_TX_SCRATCH + 0x364U)
#define CPU_LINUX_REG_SIZE     (ZYNQ_CPU_TX_SCRATCH + 0x368U)
#define CPU_LINUX_IMAGE_CODE0  (ZYNQ_CPU_TX_SCRATCH + 0x36CU)
#define CPU_LINUX_IMAGE_TEXT_LO (ZYNQ_CPU_TX_SCRATCH + 0x370U)
#define CPU_LINUX_IMAGE_TEXT_HI (ZYNQ_CPU_TX_SCRATCH + 0x374U)
#define CPU_LINUX_IMAGE_SIZE_LO (ZYNQ_CPU_TX_SCRATCH + 0x378U)
#define CPU_LINUX_IMAGE_SIZE_HI (ZYNQ_CPU_TX_SCRATCH + 0x37CU)
#define CPU_LINUX_IMAGE_MAGIC0 (ZYNQ_CPU_TX_SCRATCH + 0x380U)
#define CPU_LINUX_IMAGE_MAGIC1 (ZYNQ_CPU_TX_SCRATCH + 0x384U)
#define CPU_LINUX_IMAGE_MAGIC2 (ZYNQ_CPU_TX_SCRATCH + 0x388U)
#define CPU_LINUX_ALIAS_80000000 (ZYNQ_CPU_TX_SCRATCH + 0x38CU)
#define CPU_LINUX_ALIAS_80100000 (ZYNQ_CPU_TX_SCRATCH + 0x390U)
#define CPU_LINUX_ALIAS_80200000 (ZYNQ_CPU_TX_SCRATCH + 0x394U)
#define CPU_LINUX_ALIAS_80300000 (ZYNQ_CPU_TX_SCRATCH + 0x398U)
#define CPU_LINUX_ALIAS_80400000 (ZYNQ_CPU_TX_SCRATCH + 0x39CU)
#define CPU_LINUX_ALIAS_80500000 (ZYNQ_CPU_TX_SCRATCH + 0x3A0U)
#define CPU_LINUX_ALIAS_DTB      (ZYNQ_CPU_TX_SCRATCH + 0x3A4U)
#define CPU_LINUX_SBI_ENTRY    (ZYNQ_CPU_TX_SCRATCH + 0x280U)
#define CPU_LINUX_SBI_DTB      (ZYNQ_CPU_TX_SCRATCH + 0x284U)
#define CPU_LINUX_SBI_MCAUSE   (ZYNQ_CPU_TX_SCRATCH + 0x288U)
#define CPU_LINUX_SBI_MEPC     (ZYNQ_CPU_TX_SCRATCH + 0x28CU)
#define CPU_LINUX_SBI_LAST_EID (ZYNQ_CPU_TX_SCRATCH + 0x290U)
#define CPU_LINUX_SBI_LAST_FID (ZYNQ_CPU_TX_SCRATCH + 0x294U)
#define CPU_LINUX_SBI_LAST_ARG0 (ZYNQ_CPU_TX_SCRATCH + 0x298U)
#define CPU_LINUX_SBI_LAST_ERR (ZYNQ_CPU_TX_SCRATCH + 0x29CU)
#define CPU_LINUX_SBI_LAST_VALUE (ZYNQ_CPU_TX_SCRATCH + 0x2A0U)
#define CPU_LINUX_SBI_HARTID   (ZYNQ_CPU_TX_SCRATCH + 0x2A4U)
#define CPU_LINUX_SBI_PAYLOAD_DTB (ZYNQ_CPU_TX_SCRATCH + 0x2A8U)
#define CPU_LINUX_SBI_SPEC_ERR (ZYNQ_CPU_TX_SCRATCH + 0x2ACU)
#define CPU_LINUX_SBI_SPEC_VALUE (ZYNQ_CPU_TX_SCRATCH + 0x2B0U)
#define CPU_LINUX_SBI_PROBE_ERR (ZYNQ_CPU_TX_SCRATCH + 0x2B4U)
#define CPU_LINUX_SBI_PROBE_VALUE (ZYNQ_CPU_TX_SCRATCH + 0x2B8U)
#define CPU_LINUX_SBI_CONSOLE_CHAR (ZYNQ_CPU_TX_SCRATCH + 0x2BCU)
#define CPU_LINUX_SBI_TIMER_ERR (ZYNQ_CPU_TX_SCRATCH + 0x2C0U)
#define CPU_LINUX_SBI_TIMER_VALUE (ZYNQ_CPU_TX_SCRATCH + 0x2C4U)
#define CPU_LINUX_SBI_CMP_LO   (ZYNQ_CPU_TX_SCRATCH + 0x2C8U)
#define CPU_LINUX_SBI_CMP_HI   (ZYNQ_CPU_TX_SCRATCH + 0x2CCU)
#define CPU_LINUX_SBI_SCAUSE   (ZYNQ_CPU_TX_SCRATCH + 0x2D0U)
#define CPU_LINUX_SBI_SEPC     (ZYNQ_CPU_TX_SCRATCH + 0x2D4U)
#define CPU_LINUX_SBI_SIE      (ZYNQ_CPU_TX_SCRATCH + 0x2D8U)
#define CPU_LINUX_SBI_SIP      (ZYNQ_CPU_TX_SCRATCH + 0x2DCU)
#define CPU_LINUX_SBI_SSTATUS  (ZYNQ_CPU_TX_SCRATCH + 0x2E0U)
#define CPU_LINUX_SBI_TIME0    (ZYNQ_CPU_TX_SCRATCH + 0x2E4U)
#define CPU_LINUX_SBI_TIME1    (ZYNQ_CPU_TX_SCRATCH + 0x2E8U)
#define CPU_LINUX_ECALL_COUNT  (ZYNQ_CPU_TX_SCRATCH + 0x200U)
#define CPU_LINUX_TIME_COUNT   (ZYNQ_CPU_TX_SCRATCH + 0x204U)
#define CPU_LINUX_BASE_COUNT   (ZYNQ_CPU_TX_SCRATCH + 0x208U)
#define CPU_LINUX_CONSOLE_PUT_COUNT (ZYNQ_CPU_TX_SCRATCH + 0x20CU)
#define CPU_LINUX_CONSOLE_GET_COUNT (ZYNQ_CPU_TX_SCRATCH + 0x210U)
#define CPU_LINUX_DEBUG_COUNT  (ZYNQ_CPU_TX_SCRATCH + 0x214U)
#define CPU_LINUX_UNSUPPORTED_COUNT (ZYNQ_CPU_TX_SCRATCH + 0x218U)
#define CPU_LINUX_TRAP_COUNT   (ZYNQ_CPU_TX_SCRATCH + 0x21CU)
#define CPU_LINUX_LAST_CHAR    (ZYNQ_CPU_TX_SCRATCH + 0x220U)
#define CPU_LINUX_LAST_TIME_MEPC (ZYNQ_CPU_TX_SCRATCH + 0x224U)
#define CPU_LINUX_LAST_CONSOLE_MEPC (ZYNQ_CPU_TX_SCRATCH + 0x228U)
#define CPU_LINUX_TIMER_OFFSET_VALID (ZYNQ_CPU_TX_SCRATCH + 0x22CU)
#define CPU_LINUX_TIMER_OFFSET_LO (ZYNQ_CPU_TX_SCRATCH + 0x230U)
#define CPU_LINUX_TIMER_OFFSET_HI (ZYNQ_CPU_TX_SCRATCH + 0x234U)
#define CPU_LINUX_TIMER_MTIME_LO (ZYNQ_CPU_TX_SCRATCH + 0x238U)
#define CPU_LINUX_TIMER_MTIME_HI (ZYNQ_CPU_TX_SCRATCH + 0x23CU)
#define CPU_LINUX_RESET_TYPE (ZYNQ_CPU_TX_SCRATCH + 0x258U)
#define CPU_LINUX_RESET_REASON (ZYNQ_CPU_TX_SCRATCH + 0x25CU)
#define CPU_LINUX_RESET_MAGIC (ZYNQ_CPU_TX_SCRATCH + 0x260U)
#define CPU_LINUX_RESET_MAGIC_VALUE 0x53525354U
#define CPU_LINUX_CONSOLE_RING_BASE (ZYNQ_CPU_TX_SCRATCH + 0x000U)
#define CPU_LINUX_CONSOLE_RING_HEAD (ZYNQ_CPU_TX_SCRATCH + 0x100U)
#define CPU_LINUX_CONSOLE_RING_TOTAL (ZYNQ_CPU_TX_SCRATCH + 0x104U)
#define CPU_LINUX_CONSOLE_IN_CHAR (ZYNQ_CPU_TX_SCRATCH + 0x108U)
#define CPU_LINUX_CONSOLE_IN_VALID (ZYNQ_CPU_TX_SCRATCH + 0x10CU)
#define CPU_LINUX_CONSOLE_IN_RING_BASE (ZYNQ_CPU_TX_SCRATCH + 0x110U)
#define CPU_LINUX_CONSOLE_IN_RING_HEAD (ZYNQ_CPU_TX_SCRATCH + 0x190U)
#define CPU_LINUX_CONSOLE_IN_RING_TAIL (ZYNQ_CPU_TX_SCRATCH + 0x194U)
#define CPU_LINUX_CONSOLE_RING_WORDS 64U
#define CPU_LINUX_CONSOLE_RING_BYTES 256U
#define CPU_LINUX_CONSOLE_IN_RING_BYTES 128U
#define CPU_LINUX_HEAD_MARKER  (ZYNQ_CPU_TX_SCRATCH + 0x240U)
#define CPU_LINUX_HEAD_A0      (ZYNQ_CPU_TX_SCRATCH + 0x244U)
#define CPU_LINUX_HEAD_A1      (ZYNQ_CPU_TX_SCRATCH + 0x248U)
#define CPU_LINUX_HEAD_AMO_OLD (ZYNQ_CPU_TX_SCRATCH + 0x24CU)
#define CPU_LINUX_HEAD_BSS_LO  (ZYNQ_CPU_TX_SCRATCH + 0x250U)
#define CPU_LINUX_HEAD_BSS_HI  (ZYNQ_CPU_TX_SCRATCH + 0x254U)
#define CPU_START_MAGIC        0x43505521U
#define CPU_STATUS_WAITING     0x00000111U
#define CPU_STATUS_PASS        0x00000222U
#define CPU_STATUS_FAIL        0x00000333U
#define CPU_LOAD_TEST_PASS     0xABCD1234U
#define CPU_SUP_TRAP_MARKER    0x0000005AU
#define CPU_BOOT_DTB_VALUE     0x20010000U

#define DMA_ST_MM2S_DONE       0x00000004U
#define DMA_ST_S2MM_DONE       0x00000008U
#define DMA_ST_MM2S_ERR        0x00000010U
#define DMA_ST_S2MM_ERR        0x00000020U
#define DMA_ST_CLEAR_DONE_ERR  0x0000003CU

#define ZYNQ_CPU_DDR_CPU_BASE  0x80000000U
#define ZYNQ_CPU_DDR_PHYS_BASE 0x00000000U
#define ZYNQ_CPU_LINUX_KERNEL_CPU_ADDR 0x80400000U
#define ZYNQ_CPU_LINUX_KERNEL_PS_ADDR  0x00400000U
#define ZYNQ_CPU_DDR_HIGH_EXEC_CPU_ADDR 0x81700000U
#define ZYNQ_CPU_DDR_HIGH_EXEC_PS_ADDR  0x01700000U
#define ZYNQ_CPU_DDR_HIGH_DATA_CPU_ADDR 0x81710000U
#define ZYNQ_CPU_DDR_HIGH_DATA_PS_ADDR  0x01710000U
#define ZYNQ_CPU_DDR_HIGH_AMO_CPU_ADDR  0x81720000U
#define ZYNQ_CPU_DDR_HIGH_AMO_PS_ADDR   0x01720000U
#define ZYNQ_CPU_LINUX_DTB_CPU_ADDR    0x82000000U
#define ZYNQ_CPU_LINUX_DTB_PS_ADDR     0x02000000U
#define ZYNQ_CPU_LINUX_IMAGE_CODE0     0x0000106FU
#define ZYNQ_CPU_LINUX_IMAGE_TEXT_LO   0x00400000U
#define ZYNQ_CPU_LINUX_IMAGE_MAGIC0    0x43534952U
#define ZYNQ_CPU_LINUX_IMAGE_MAGIC1    0x00000056U
#define ZYNQ_CPU_LINUX_IMAGE_MAGIC2    0x05435352U
#define ZYNQ_CPU_DTB_MAGIC_RAW         0xEDFE0DD0U
#define CPU_DDR_EXEC_WORDS     64U
#define CPU_SBI_PAYLOAD_WORDS  128U
#define CPU_LINUX_CONTRACT_WORDS 1024U

#define DMA_WORDS              16U
#define DMA_BYTES              (DMA_WORDS * sizeof(u32))

extern u32 dma_src[DMA_WORDS];
extern u32 dma_dst[DMA_WORDS];
extern u32 cpu_dma_src[DMA_WORDS];
extern u32 cpu_dma_dst[DMA_WORDS];
extern u32 cpu_ddr_probe[32];
extern u32 cpu_ddr_exec[CPU_DDR_EXEC_WORDS];
extern u32 cpu_sbi_payload[CPU_SBI_PAYLOAD_WORDS];
extern u32 cpu_linux_contract[CPU_LINUX_CONTRACT_WORDS];

int load_zx32_elf_into_imem(const u8 *elf, u32 elf_size, u32 *loaded_words_out, u32 *entry_out);
int wait_for_dma(u32 done_mask, u32 err_mask, u32 *status_out);
int wait_for_cpu(u32 *status_out);

int run_datamover_loopback(void);
int run_cpu_datamover_loopback(void);
int run_cpu_bram_load_test(void);
int run_cpu_elf_load_test(void);
int run_cpu_ddr_access_smoke_test(void);
int run_cpu_custom_datamover_test(void);
int run_cpu_entry_smoke_test(void);
int run_cpu_trap_smoke_test(void);
int run_cpu_ddr_exec_smoke_test(void);
int run_cpu_ddr_high_access_smoke_test(void);
int run_cpu_ddr_high_exec_smoke_test(void);
int run_cpu_ddr_high_amo_smoke_test(void);
int run_cpu_sbi_smoke_test(void);
int run_cpu_sbi_timer_smoke_test(void);
int run_cpu_linux_contract_smoke_test(void);
int run_cpu_linux_image_layout_smoke_test(void);
int run_cpu_linux_sbi_smoke_test(void);
int run_cpu_supervisor_smoke_test(void);
int run_cpu_supervisor_timer_smoke_test(void);
int run_cpu_boot_payload_smoke_test(void);
int run_cpu_supervisor_counter_smoke_test(void);

#endif
